# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.7
      env: TOXENV=py37-test
    - python: 3.7
      env: TOXENV=run-blackcheck
    - python: 3.7
      env: TOXENV=run-isortcheck
install:
  # any failure stops the build
  - set -e
  - hash -r
  - pip install tox coveralls
  - pip freeze
script:
  - tox -e $TOXENV
after_success:
  - if [[ $TOXENV == 'test37' ]]; then coveralls; fi
