# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.7
      env: TOXENV=py37-test
    - python: 3.7
      env: TOXENV=run-blackcheck
    - python: 3.7
      env: TOXENV=run-isortcheck
install:
  # any failure stops the build
  - set -e
  - hash -r
  - pip install tox
  - pip freeze
script:
  - tox -e $TOXENV
after_success:
  # coveralls is prone to random failures (which would fail the Travis job), so we'll handle those silently
  - if [[ "${TOXENV}" =~ test ]]; then tox -e $(echo "${TOXENV}" | sed s/test/runcmd/) -- coveralls -v || echo "Cannot upload to coveralls"; fi
notifications:
  webhooks: https://coveralls.io/webhook
